MVC-2020-Templates/Controllers/SecureController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using MVC_2020_Business.Models;
using MVC_2020_Business.Services;
using MVC_2020_Template.Helpers;
using MVC_2020_Template.Models;
using Newtonsoft.Json;

namespace MVC_2020_Template.Controllers
{
    public class SecureController : Controller
    {
        private readonly IHostingEnvironment _env;
        public readonly IConfiguration _conf;
        public SecureController(IHostingEnvironment env, IConfiguration conf)
        {
            _env = env;
            _conf = conf;
        }
        // GET: Secure
        public ActionResult Index()
        {
            new Authentication(HttpContext, _env, _conf);
            //var serverVars = HttpContext.Features.Get<IServerVariablesFeature>();
            //var iupiSession = serverVars?["iupi"]?.ToString();
            //var emailSession = serverVars?["mail"]?.ToString();
            //ViewBag.iupiSession = iupiSession;
            //ViewBag.emailSession = emailSession;

            ViewBag.isLoggedin = Session.SessionActive;
            
            return View();
        }

        public ActionResult Logout()
        {
            HttpContext.Session.Clear();
            Session.Logout();
            return Redirect("/secure/Shibboleth.sso/Logout");
        }
    }
}

MVC-2020-Templates/Views/Shared/2ColsHome_Layout.cshtml
@{
    Layout = "Home_Layout";
}
<div class="wide content">
    @RenderBody()
</div>

MVC-2020-Templates/Views/Shared/Form_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UA CRIS</title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet"> <!-- bootstrap para icons-->
    <link rel="shortcut icon" href="//static.ua.pt/favicon.ico" />
    <link rel="stylesheet" href="//static.ua.pt/css/semanticua/2.0b/dist/semantic.min.css" />
    <link rel="stylesheet" href="~/css/site.min.css" />


    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
</head>
<body>

    <div class="service area">
        <div class="limiter">
            <div class="common">
                <a href="https://www.ua.pt/pt/noticias" target="_blank">Notícias</a> | <a href="https://www.ua.pt/pt/agenda" target="_blank">Agenda</a> |
                <a href="https://www.facebook.com/universidadedeaveiro/" target="_blank"><i class="facebook f icon"></i></a> |
                <a href="https://www.instagram.com/universidadedeaveiro/?hl=pt" target="_blank"><i class="instagram icon"></i></a>
            </div>
            <div class="shortcuts">
                <a href="https://www.ua.pt/pt/comunidade" target="_blank">Comunidade ua</a>
                <a href="https://www.ua.pt/sbidm/biblioteca/externos" target="_blank">Utilizador externo</a>
            </div>
            <div class="session">
                @{ var session = new MVC_2020_Template.Helpers.Session(Context.Session);


                    @if (@MVC_2020_Template.Helpers.Session.SessionActive)
                    {
                        <span style="color:white">@session.FullName</span>
                        @*<a href="/Secure/Logout">&nbsp; Logout <i class="outline user icon"></i></a>*@
                        <i class="outline user icon"></i>@Html.ActionLink("Sair", "Logout", "Secure", null)
                    }
                    else
                    {
                        @*<span style="color:white">@MVC_2020_Template.Helpers.Session.FullName</span>*@
                        @*<a href="/Secure/Index"> Entrar <i class="outline user icon"></i></a>*@
                        <i class="outline user icon"></i>@Html.ActionLink("Entrar", "Index", "Secure", null)
                        //@Html.ActionLink("login", "Index", "Secure", null, new { @class = "image-button login", @title = "login", @alt = "login" })
                    }
                }
                @*<a href="/Secure/auto">Entrar <i class="outline user icon"></i></a>*@
            </div>
            @*<div id="IconsLeft">
                <div class="float_right">
                    <span class="top-menu-name">

                </span>
            </div>
            <div class="float_right">
                @if (session.SessionActive)
                {
                    @Html.ActionLink("logout", "Logout", "Home", null, new { @class = "image-button logout", @title = "logout", @alt = "logout" })
                }
                else
                {
                    @Html.ActionLink("login", "Auto", "Secure", null, new { @class = "image-button login", @title = "login", @alt = "login" })
                }
            </div>
            <div class="clear"></div>
        </div>*@
        </div>
    </div>

    <div class="system area">
        <div class="limiter">
            <div class="logo">
                <a href="https://www.ua.pt/" target="_blank">
                    <img src="//static.ua.pt/images/ua/logo-black.svg" alt="" />
                </a>
            </div>
            <div class="identity">
                <a href="@Url.Action("MyPublications","Home",null)">
                    <h1>UA CRIS</h1>
                </a>
            </div>
            <div class="menu">
                <a class="js-menu-toggle" href="#"><i class="bars icon"></i></a>
            </div>
            <nav class="ua"></nav>
        </div>
    </div>
   
            @RenderBody()
    

    <footer>
        @*<div class="section">
            <div class="limiter">
                <div class="info">
                    Links rápidos
                </div>
            </div>
        </div>*@
        <div class="section">
            <div class="limiter">
                <div class="info">
                    &copy; Universidade de Aveiro 2020
                </div>
            </div>
        </div>
    </footer>

    <script src="//static.ua.pt/js/jquery/jquery-3.2.1.min.js"></script>
    <script src="//static.ua.pt/css/semanticua/2.0b/dist/semantic.min.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MVC-2020-Templates/Views/Shared/Home_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UA CRIS</title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet"> <!-- bootstrap para icons-->
    <link rel="shortcut icon" href="//static.ua.pt/favicon.ico" />
    <link rel="stylesheet" href="//static.ua.pt/css/semanticua/2.0b/dist/semantic.min.css" />
    <link rel="stylesheet" href="~/css/site.min.css" />
    
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
</head>
<body>

    <div class="service area">
        <div class="limiter">
            <div class="common">
                <a href="https://www.ua.pt/pt/noticias" target="_blank">Notícias</a> | <a href="https://www.ua.pt/pt/agenda" target="_blank">Agenda</a> |
                <a href="https://www.facebook.com/universidadedeaveiro/" target="_blank"><i class="facebook f icon"></i></a> |
                <a href="https://www.instagram.com/universidadedeaveiro/?hl=pt" target="_blank"><i class="instagram icon"></i></a>
            </div>
            <div class="shortcuts">
                <a href="https://www.ua.pt/pt/comunidade" target="_blank">Comunidade ua</a>
                <a href="https://www.ua.pt/sbidm/biblioteca/externos" target="_blank">Utilizador externo</a>
            </div>
            <div class="session">
                @{ var session = new MVC_2020_Template.Helpers.Session(Context.Session);


                    @if (@MVC_2020_Template.Helpers.Session.SessionActive)
                    {
                        <span style="color:white">@session.FullName</span>
                        @*<a href="/Secure/Logout">&nbsp; Logout <i class="outline user icon"></i></a>*@
                        <i class="outline user icon"></i>@Html.ActionLink("Sair", "Logout", "Secure", null)
                    }
                    else
                    {
                        @*<span style="color:white">@MVC_2020_Template.Helpers.Session.FullName</span>*@
                        @*<a href="/Secure/Index"> Entrar <i class="outline user icon"></i></a>*@
                        <i class="outline user icon"></i>@Html.ActionLink("Entrar", "Index", "Secure", null)
                        //@Html.ActionLink("login", "Index", "Secure", null, new { @class = "image-button login", @title = "login", @alt = "login" })
                    }
                }
                @*<a href="/Secure/auto">Entrar <i class="outline user icon"></i></a>*@
            </div>
            @*<div id="IconsLeft">
                <div class="float_right">
                    <span class="top-menu-name">

                </span>
            </div>
            <div class="float_right">
                @if (session.SessionActive)
                {
                    @Html.ActionLink("logout", "Logout", "Home", null, new { @class = "image-button logout", @title = "logout", @alt = "logout" })
                }
                else
                {
                    @Html.ActionLink("login", "Auto", "Secure", null, new { @class = "image-button login", @title = "login", @alt = "login" })
                }
            </div>
            <div class="clear"></div>
        </div>*@
        </div>
    </div>

    <div class="system area">
        <div class="limiter">
            <div class="logo">
                <a href="https://www.ua.pt/" target="_blank">
                    <img src="//static.ua.pt/images/ua/logo-black.svg" alt="" />
                </a>
            </div>
            <div class="identity">
                <a href="@Url.Action("MyPublications","Home",null)">
                    <h1>UA CRIS</h1>
                </a>
            </div>
            <div class="menu">

                <a class="js-menu-toggle" href="#"><i class="bars icon"></i></a>
            </div>
            <nav class="ua"></nav>
        </div>
    </div>
    
    <div align="center"><img src="~/images/ua_reitoria.jpg" width="100%" height="450px"></div>
    <div class="main area">
        <div class="limiter">
            <div class="menu">
                <nav class="ua">
                    <ul data-arrow="before">
                        <li>
                            @Html.ActionLink("Home", "Home", "Home", null)
                        </li>
                        @{if (MVC_2020_Template.Helpers.Session.SessionActive)
                            {
                                <li>
                                    @Html.ActionLink("Perfil", "Perfil", "Home", null)
                                </li>
                                <li>
                                    @Html.ActionLink("Minhas Publicações", "MyPublications", "Home", null)
                                </li>
                                <li>
                                    @Html.ActionLink("Importar Publicações", "Publicacoes", "Home", null)
                                </li>
                                <li>
                                    @Html.ActionLink("Publicações Guardadas", "PublicacoesSalvas", "Home", null)
                                </li>
                                <li>
                                    @Html.ActionLink("Sobre", "Sobre", "Home", null)
                                </li>
                            }
                        }
                    </ul>
                </nav>
            </div>
            @RenderBody()
        </div>
    </div>


    <footer>
        @*<div class="section">
            <div class="limiter">
                <div class="info">
                    Links rápidos
                </div>
            </div>
        </div>*@
        <div class="section">
            <div class="limiter">
                <div class="info">
                    &copy; Universidade de Aveiro 2020
                </div>
            </div>
        </div>
    </footer>

    <script src="//static.ua.pt/js/jquery/jquery-3.2.1.min.js"></script>
    <script src="//static.ua.pt/css/semanticua/2.0b/dist/semantic.min.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MVC-2020-Templates/Views/Shared/_2ColsLayout.cshtml
@{
    Layout = "_MasterLayout";
}
<div class="wide content">
    @RenderBody()
</div>

MVC-2020-Templates/Views/Shared/_3ColsLayout.cshtml
@{
    Layout = "_MasterLayout";
}
<div class="content">
    @RenderBody()
</div>
<div class="side">
    @if (IsSectionDefined("RightColumn"))
    {
        @RenderSection("RightColumn")
    }
</div>

MVC-2020-Templates/Views/Shared/_MasterLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UA CRIS</title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet"> <!-- bootstrap para icons-->
    <link rel="shortcut icon" href="//static.ua.pt/favicon.ico" />
    <link rel="stylesheet" href="//static.ua.pt/css/semanticua/2.0b/dist/semantic.min.css" />
    <link rel="stylesheet" href="~/css/site.min.css" />
    <link rel="stylesheet" href="~/css/meuCSS.css" />

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
</head>
<body>

    <div class="service area">
        <div class="limiter">
            <div class="common">
                <a href="https://www.ua.pt/pt/noticias" target="_blank">Notícias</a> | <a href="https://www.ua.pt/pt/agenda" target="_blank">Agenda</a> |
                <a href="https://www.facebook.com/universidadedeaveiro/" target="_blank"><i class="facebook f icon"></i></a> |
                <a href="https://www.instagram.com/universidadedeaveiro/?hl=pt" target="_blank"><i class="instagram icon"></i></a>
            </div>
            <div class="shortcuts">
                <a href="https://www.ua.pt/pt/comunidade" target="_blank">Comunidade ua</a>
                <a href="https://www.ua.pt/sbidm/biblioteca/externos" target="_blank">Utilizador externo</a>
            </div>
            <div class="session">
                @{ var session = new MVC_2020_Template.Helpers.Session(Context.Session);


                @if (@MVC_2020_Template.Helpers.Session.SessionActive)
                {
                <span style="color:white">@MVC_2020_Template.Helpers.Session.FullName</span>
                @*<a href="/Secure/Logout">&nbsp; Logout <i class="outline user icon"></i></a>*@
                    <i class="outline user icon"></i>@Html.ActionLink("Sair", "Logout", "Secure", null)
                }
                else
                {
                @*<span style="color:white">@MVC_2020_Template.Helpers.Session.FullName</span>*@
                @*<a href="/Secure/Index"> Entrar <i class="outline user icon"></i></a>*@
                    <i class="outline user icon"></i>@Html.ActionLink("Entrar", "Index", "Secure", null)
                    //@Html.ActionLink("login", "Index", "Secure", null, new { @class = "image-button login", @title = "login", @alt = "login" })
                }
                }
                @*<a href="/Secure/auto">Entrar <i class="outline user icon"></i></a>*@
            </div>
            @*<div id="IconsLeft">
                <div class="float_right">
                    <span class="top-menu-name">

                </span>
            </div>
            <div class="float_right">
                @if (session.SessionActive)
                {
                    @Html.ActionLink("logout", "Logout", "Home", null, new { @class = "image-button logout", @title = "logout", @alt = "logout" })
                }
                else
                {
                    @Html.ActionLink("login", "Auto", "Secure", null, new { @class = "image-button login", @title = "login", @alt = "login" })
                }
            </div>
            <div class="clear"></div>
        </div>*@
        </div>
    </div>

    <div class="system area">
        <div class="limiter">
            <div class="logo">
                <a href="https://www.ua.pt/" target="_blank">
                    <img src="//static.ua.pt/images/ua/logo-black.svg" alt="" />
                </a>
            </div>
            <div class="identity">
                <a href="@Url.Action("MyPublications","Home",null)"><h1>UA CRIS</h1></a>
            </div>
            <div class="menu">
                <a class="js-menu-toggle" href="#"><i class="bars icon"></i></a>
            </div>
            <nav class="ua"></nav>
        </div>
    </div>

    <div class="main area">
        <div class="limiter">
            <div class="menu">
                <nav class="ua">
                    <ul data-arrow="before">
                        @*<li>
            @Html.ActionLink("Home", "Home", "Home", null)
        </li>*@
                        @*<li>
            @Html.ActionLink("Instruções", "Readme", "Home", null)
        </li>*@
                        @*@{if (MVC_2020_Template.Helpers.Session.SessionActive)*@
                        @*//   {*@

                        <li>
                            @Html.ActionLink("Perfil", "Perfil", "Home", null)
                        </li>
                        <li>
                            @Html.ActionLink("Minhas Publicações", "MyPublications", "Home", null)
                        </li>
                        <li>
                            @Html.ActionLink("Importar Publicações", "Publicacoes", "Home", null)
                        </li>
                        <li>
                            @Html.ActionLink("Publicações Guardadas", "PublicacoesSalvas", "Home", null)
                        </li>
                        <li>
                            @Html.ActionLink("Unidades de Investigação", "Index", "Org", null)
                        </li>
                        <li>
                            @Html.ActionLink("Projetos", "Projects", "Home", null)
                        </li>
                        <li>
                            @Html.ActionLink("Sobre", "Sobre", "Home", null)
                        </li>
                        <li>
                            @Html.ActionLink("Administrador", "Admin", "Home", null)
                        </li>
                        @*<li>
            @Html.ActionLink("Exemplo", "Index", "Home", null)
            <ul>
                <li>@Html.ActionLink("Conteúdo", "Content", "Home", null)</li>
                <li>@Html.ActionLink("Formulário", "Forms", "Home", null)</li>
                <li>@Html.ActionLink("Erro", "Errors", "Home", null)</li>
            </ul>
        </li>*@
                        @*//  }*@
                        @*}*@
                    </ul>
                </nav>
            </div>
            @RenderBody()
        </div>
    </div>


    <footer>
        @*<div class="section">
            <div class="limiter">
                <div class="info">
                    Links rápidos
                </div>
            </div>
        </div>*@
        <div class="section">
            <div class="limiter">
                <div class="info">
                    &copy; Universidade de Aveiro 2020
                </div>
            </div>
        </div>
    </footer>

    <script src="//static.ua.pt/js/jquery/jquery-3.2.1.min.js"></script>
    <script src="//static.ua.pt/css/semanticua/2.0b/dist/semantic.min.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MVC-2020-Templates/Views/Shared/teste.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC 2020 Template</title>
    <link rel="shortcut icon" href="//static.ua.pt/favicon.ico" />
    <link rel="stylesheet" href="//static.ua.pt/css/semanticua/2.0b/dist/semantic.min.css" />
    <link rel="stylesheet" href="~/css/site.min.css" />

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
</head>
<body>

    <div class="service area">
        <div class="limiter">
            <div class="common">
                <a href="#">Notícias</a> | <a href="#">Agenda</a> |
                <a href="#"><i class="facebook f icon"></i></a> |
                <a href="#"><i class="instagram icon"></i></a>
            </div>
            <div class="shortcuts">
                <a href="#">Comunidade ua</a>
                <a href="#">Utilizador externo</a>
            </div>
            <div class="session">
                @{ var session = new MVC_2020_Template.Helpers.Session(Context.Session);


                    @if (@MVC_2020_Template.Helpers.Session.SessionActive)
                    {
                        <span style="color:white">@MVC_2020_Template.Helpers.Session.FullName</span>
                        @*<a href="/Secure/Logout">&nbsp; Logout <i class="outline user icon"></i></a>*@
                        <i class="outline user icon"></i>@Html.ActionLink("Sair", "Logout", "Secure", null)
                    }
                    else
                    {
                        @*<span style="color:white">@MVC_2020_Template.Helpers.Session.FullName</span>*@
                        @*<a href="/Secure/Index"> Entrar <i class="outline user icon"></i></a>*@
                        <i class="outline user icon"></i>@Html.ActionLink("Entrar", "Index", "Secure", null)
                        //@Html.ActionLink("login", "Index", "Secure", null, new { @class = "image-button login", @title = "login", @alt = "login" })
                    }
                }
                @*<a href="/Secure/auto">Entrar <i class="outline user icon"></i></a>*@
            </div>
            @*<div id="IconsLeft">
                        <div class="float_right">
                            <span class="top-menu-name">

                        </span>
                    </div>
                    <div class="float_right">
                        @if (session.SessionActive)
                        {
                            @Html.ActionLink("logout", "Logout", "Home", null, new { @class = "image-button logout", @title = "logout", @alt = "logout" })
                        }
                        else
                        {
                            @Html.ActionLink("login", "Auto", "Secure", null, new { @class = "image-button login", @title = "login", @alt = "login" })
                        }
                    </div>
                    <div class="clear"></div>
                </div>*@
        </div>
    </div>

    <div class="system area">
        <div class="limiter">
            <div class="logo">
                <a href="https://www.ua.pt/">
                    <img src="//static.ua.pt/images/ua/logo-black.svg" alt="" />
                </a>
            </div>
            <div class="identity">
                <h1>UA CRIS</h1>
            </div>
            <div class="tools">
                <a href="#" title="pesquisa" aria-label="pesquisa">
                    <i class="search icon"></i>
                </a>
                <a href="#" title="versão inglesa">EN</a>
            </div>
            <div class="menu">
                <a class="js-menu-toggle" href="#"><i class="bars icon"></i></a>
            </div>
            <nav class="ua"></nav>
        </div>
    </div>
   
            @RenderBody()
    

    <footer>
        <div class="section">
            <div class="limiter">
                <div class="info">
                    Links rápidos
                </div>
            </div>
        </div>
        <div class="section">
            <div class="limiter">
                <div class="info">
                    &copy; Universidade de Aveiro 2020
                </div>
            </div>
        </div>
    </footer>

    <script src="//static.ua.pt/js/jquery/jquery-3.2.1.min.js"></script>
    <script src="//static.ua.pt/css/semanticua/2.0b/dist/semantic.min.js"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>